version: '3.8'

volumes:
  node-modules:
  client:

services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-client", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: "yarn dev"
  
  server:
    build:
      context: ./server
    ports:
      - "5000:8000"
    volumes:
      - ./server:/var/www/adflix/server
    depends_on:
      - redis
    working_dir: /var/www/adflix/server
    dns:
      - 1.1.1.1
      - 1.0.0.1

    db:
      image: mysql:latest
      restart: always
      env_file: ./server/.env
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}