version: '3.8'

services:
  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  client:
    build:
      context: ./client
    ports:
      - ${DOCKER_VITE_PORT}:3000
    volumes:
      - ./client:/app/client
      - ./.env:/app/client/.env
    command: ["sh", "entrypoint.sh"]
    working_dir: /app/client

  python:
    build: ./python
    env_file:
      - .env
    environment:
      - PWD=${PWD}
  
  server:
    build:
      context: ./server
    ports:
      #octane server
      - target: 8000
        host_ip: 127.0.0.1
        published: ${DOCKER_SERVER_PORT}
        protocol: tcp
        mode: host
    volumes:
      - ./server:/var/www/adflix/server
      - ./.env:/var/www/adflix/server/.env
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    working_dir: /var/www/adflix/server
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - target: 3306
        host_ip: 127.0.0.1
        published: ${DOCKER_DB_PORT}
        protocol: tcp
        mode: host
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 30s
      retries: 100
    