version: '3.8'

volumes:
  node-modules:
  client:

services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-client", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: "yarn dev"