name: "Migrate"
on:
  push:
    branches:
      - master
    paths:
      - 'server/Dockerfile'
      - 'server/entrypoint.sh'
      - 'docker-compose.yml'
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: /var/www/adflix
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull code
      run: git pull
    - name: Build and Up Docker Compose
      run: docker compose up --build -d