name: "Laravel Migrate"
on:
  push:
    branches:
      - master
    paths:
      - 'server/database/migrations/**'
  workflow_dispatch:
    inputs:
      reset:
        description: 'Reset the database'
        required: false
        default: false
        type: boolean
    inputs:
      seed:
        description: 'Seed the database'
        required: false
        default: false
        type: boolean

defaults:
  run:
    working-directory: /var/www/adflix
    
jobs:
  reset:
    runs-on: self-hosted
    if: ${{ github.event.inputs.reset == 'true' }}
    steps:
    - name: Run Laravel migrations
      run: docker compose exec server php artisan migrate:fresh
  migrate:
    runs-on: self-hosted
    if: ${{ github.event.inputs.reset == 'false' }}
    steps:
    - name: Pull code
      run: git pull
    - name: Run Laravel migrations
      run: docker compose exec server php artisan migrate
  seed:
    runs-on: self-hosted
    if: ${{ github.event.inputs.seed == 'true' }}
    needs: [reset, migrate]
    steps:
    - name: Seed the database
      run: docker compose exec server php artisan db:seed
