name: "Laravel Migrate"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'adflix-dev'
        options:
          - 'adflix-dev'
          - 'adflix'
      reset:
        type: boolean
        description: 'Reset database'
        required: true
        default: false
      seed:
        type: boolean
        description: 'Seed database'
        required: true
        default: true
    
jobs:
  migrate:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/${{ github.event.inputs.environment }}
    steps:
      - name: Reset Laravel migrations
        run: docker compose exec server php artisan migrate:reset
        if: ${{ github.event.inputs.reset == true }}
      - name: Run Laravel migrations
        run: docker compose exec server php artisan migrate
      - name: Seed database
        run: docker compose exec server php artisan db:seed
        if: ${{ github.event.inputs.seed == true }}
      
