name: "Deploy Server"
on:
  push:
    branches:
      - master
    paths:
      - server
  workflow_dispatch:

defaults:
  run:
    working-directory: /var/www/adflix
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull code
      run: git pull
    - name: Build and up Docker Compose
      run: docker compose up -d --build
    - name: Check running containers
      run: docker compose ps -a
    - name: Check logs
      run: docker compose logs server --tail 50
    - name: Run Laravel migrations
      run: docker compose exec server php artisan:migrate
