name: "Deploy Server"
on:
  push:
    branches:
      -master
  workflow_dispatch:

defaults:
  run:
    working-directory: /var/www/adflix
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: Move files
      run: mv $GITHUB_WORKSPACE /var/www/adflix
    - name: Build and up Docker Compose
      run: docker compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker compose logs server --tail 50
    - name: Run Laravel migrations
      run: docker compose exec php artisan:migrate
